### ISSUE TITLE
Issue with delegation history endpoint 

### ISSUE THREAD

**Issue by Vardominator** [blockfrost/openapi#181]
I'm having issues with the following endpoints:

History: https://cardano-mainnet.blockfrost.io/api/v0/accounts/stake1ux5lwm698vumlj9sa3pj3svuqmz33up0qhj7apdgzvhzzxs7dc83m/history

Current: https://cardano-mainnet.blockfrost.io/api/v0/accounts/stake1ux5lwm698vumlj9sa3pj3svuqmz33up0qhj7apdgzvhzzxs7dc83m

For this particular stake address, and a few others that I'm testing, the results don't make any sense. The history endpoint is showing data from only the current epoch, and the current endpoint is showing data from one of the historical epochs. 

Can you please help me? I have an urgent deadline to release something that relies heavily on your API.

**Comment by sorki** [comment]
Hi, the example you've posted makes sense to me -

The current endpoint query `active_epoch` is `Epoch of the most recent action - registration or deregistration` which in this case is epoch `310`. That means that the account stake delegation was registered in epoch `310` while the history endpoint is showing epoch `312` - the epoch in which the delegation became active. Remember it takes *two epochs* for registration (stake delegation)  to become active.

**Comment by 1000101** [comment]
Hi, just glancing at the results, I think API is right.

https://cardano-mainnet.blockfrost.io/api/v0/accounts/stake1ux5lwm698vumlj9sa3pj3svuqmz33up0qhj7apdgzvhzzxs7dc83m:
```
active: true
active_epoch: 310
controlled_amount: "19308824643"
```
This means that the stake address has been registered at epoch 310, is active (has not been deregistered) and currently holds sum of 19308824643 Lovelaces.

https://cardano-mainnet.blockfrost.io/api/v0/accounts/stake1ux5lwm698vumlj9sa3pj3svuqmz33up0qhj7apdgzvhzzxs7dc83m/history:
```
active_epoch:312,
amount: "19308824643",
```
This means that the stake snapshot has been taken at epoch 310 and hence is active in epoch 312, with snapshot being 19308824643 Lovelaces at the time being (which hasn't changed since).

> I'm having issues with the following endpoints:
> 
> History: https://cardano-mainnet.blockfrost.io/api/v0/accounts/stake1ux5lwm698vumlj9sa3pj3svuqmz33up0qhj7apdgzvhzzxs7dc83m/history
> 
> Current: https://cardano-mainnet.blockfrost.io/api/v0/accounts/stake1ux5lwm698vumlj9sa3pj3svuqmz33up0qhj7apdgzvhzzxs7dc83m
> 
> For this particular stake address, and a few others that I'm testing, the results don't make any sense. The history endpoint is showing data from only the current epoch, and the current endpoint is showing data from one of the historical epochs.
> 
> Can you please help me? I have an urgent deadline to release something that relies heavily on your API.

Hi, thanks for the question! Just by glancing at the results, I think API is right.

https://cardano-mainnet.blockfrost.io/api/v0/accounts/stake1ux5lwm698vumlj9sa3pj3svuqmz33up0qhj7apdgzvhzzxs7dc83m:
```
active: true
active_epoch: 310
controlled_amount: "19308824643"
```
This means that the stake address has been registered at epoch 310, is active (has not been deregistered) and currently holds sum of 19308824643 Lovelaces.

https://cardano-mainnet.blockfrost.io/api/v0/accounts/stake1ux5lwm698vumlj9sa3pj3svuqmz33up0qhj7apdgzvhzzxs7dc83m/history:
```
active_epoch:312,
amount: "19308824643",
```
This means that the stake snapshot has been taken at epoch 310 and hence is active in epoch 312, with snapshot being 19308824643 Lovelaces at the time being (which hasn't changed since).

**Comment by Vardominator** [comment]
@sorki @1000101 that makes sense. thank you! Is there a way to simply get a history of delegation at every epoch, disregarding the 3 epochs required to become active?

**Comment by Vardominator** [comment]
@sorki @1000101 ?

**Comment by 1000101** [comment]
> @sorki @1000101 that makes sense. thank you! Is there a way to simply get a history of delegation at every epoch, disregarding the 3 epochs required to become active?

Delegation only counts when it becomes active, so the only valid delegation history is this one.
However, you might also be interested in [registration transactions](https://docs.blockfrost.io/#tag/Cardano-Accounts/paths/~1accounts~1{stake_address}~1registrations/get) - this would tell you exactly how the account moved through the pools, but it won't tell you their live stake at that moment as it's not really relevant.
