### ISSUE TITLE
Investigate CIP-25 metadata parsing

### ISSUE THREAD

**Issue by vladimirvolek** [blockfrost/openapi#375]
Policy ID 62a866f7cd0b77220f4f32538a5123a9dc10c130f1681a191d324c40.

**Comment by slowbackspace** [comment]
they are trying to use cip25v1 but they are doing it wrong

From CIP25:
> In version 1 the asset_name must be utf-8 encoded and in text format for the key in the metadata map.

> In version 1 the policy_id must be in text format for the key in the metadata map.

eg. if asset name is “readme” in utf8 metadata map must contain `726561646D65`.

but they don’t have valid utf8 asset name (`9a56`) and their json metadata look like this

```
{
        "62a866f7cd0b77220f4f32538a5123a9dc10c130f1681a191d324c40": {
          "330d": {
            name: "MNTX airdrop claim",
            image: "ipfs://QmTCmbEj82q9WxH4zjniMnVuX2pzzkpvZFMV2imkeo8dTX",
            amount: "2033.077257",
            mediaType: "image/jpeg",
          },
          "9a56": {
            name: "MNTX airdrop claim",
            image: "ipfs://QmTCmbEj82q9WxH4zjniMnVuX2pzzkpvZFMV2imkeo8dTX",
            amount: "466.017709",
            mediaType: "image/jpeg",
          },
          c3af: {
            name: "MNTX airdrop claim",
            image: "ipfs://QmTCmbEj82q9WxH4zjniMnVuX2pzzkpvZFMV2imkeo8dTX",
            amount: "199.007562",
            mediaType: "image/jpeg",
          },
          dc69: {
            name: "MNTX airdrop claim",
            image: "ipfs://QmTCmbEj82q9WxH4zjniMnVuX2pzzkpvZFMV2imkeo8dTX",
            amount: "537.020407",
            mediaType: "image/jpeg",
          },
        },
      },
```

so basically in their case the assetname = lookup key which is not how it works in v1. they should have minted it as v2 (and encode it as bytes instead of text)

**Comment by vladimirvolek** [comment]
@SynthLuvr We are implementing a fix.
